<?php

namespace AppBundle\Repository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $products = $this->createQueryBuilder('p');
        $products->where('p.isAvailable = 1','p.quantity > 0');
        return $products->getQuery()->getResult();
    }



}
